services:
  postgres_db:
    image: postgres:17
    container_name: springboot_db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meal_planner
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meal_planner"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: leetx11/meal-backend:1.0
    environment:
      - DB_URL=jdbc:postgresql://postgres_db:5432/meal_planner
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8085:8085"
    depends_on:
      postgres_db:
        condition: service_healthy

  frontend:
    image: leetx11/meal-frontend:1.0
    environment:
      - API_TARGET=http://backend:8085
    ports: 
      - "4200:4000"
    depends_on:
      - backend

volumes:
  pgdata:
