spring.application.name=meal-catalogue-planner
server.port=8085

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/meal_planner}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# PostgreSQL JDBC driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Let Hibernate create/update tables based on @Entity classes
spring.jpa.hibernate.ddl-auto=update

# Show SQL in terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
